// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package balls;

public final class Player_Stub
    extends java.rmi.server.RemoteStub
    implements balls.IF_Meet, balls.IF_Play, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_hereIAm_0;
    private static java.lang.reflect.Method $method_throwBall_1;
    private static java.lang.reflect.Method $method_yourPeers_2;
    
    static {
	try {
	    $method_hereIAm_0 = balls.IF_Meet.class.getMethod("hereIAm", new java.lang.Class[] {balls.IF_Play.class});
	    $method_throwBall_1 = balls.IF_Play.class.getMethod("throwBall", new java.lang.Class[] {});
	    $method_yourPeers_2 = balls.IF_Play.class.getMethod("yourPeers", new java.lang.Class[] {java.util.ArrayList.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public Player_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of hereIAm(IF_Play)
    public void hereIAm(balls.IF_Play $param_IF_Play_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_hereIAm_0, new java.lang.Object[] {$param_IF_Play_1}, -7545272408087593656L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of throwBall()
    public void throwBall()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_throwBall_1, null, 4114628475425292488L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of yourPeers(ArrayList)
    public void yourPeers(java.util.ArrayList $param_ArrayList_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_yourPeers_2, new java.lang.Object[] {$param_ArrayList_1}, 442218542557541662L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
